/**
 * AutoProducerAgent — AI-powered live show direction
 *
 * Ghost Producer as a standalone agent. Analyzes audio,
 * switches cameras, triggers graphics, marks highlights.
 *
 * Calls the WAVE capability routes POST /v1/ghost-producer, /v1/switcher,
 * /v1/graphics-engine and /v1/replay. Each needs its own `<capability>:write`
 * scope on the key (see https://gateway.wave.online/.well-known/wave-scopes.json).
 */

import { WaveAgent, type WaveAgentConfig } from '../agents/WaveAgent';

interface AutoProducerConfig extends Omit<WaveAgentConfig, 'agentType'> {
  readonly switcherId: string;
  readonly style?: 'conference' | 'interview' | 'sports' | 'worship' | 'education';
  readonly confidenceThreshold?: number;
}

export class AutoProducerAgent extends WaveAgent {
  private readonly switcherId: string;
  private readonly style: string;
  private readonly confidenceThreshold: number;

  constructor(config: AutoProducerConfig) {
    super({ ...config, agentType: 'auto_producer' });
    this.switcherId = config.switcherId;
    this.style = config.style ?? 'conference';
    this.confidenceThreshold = config.confidenceThreshold ?? 0.7;
  }

  override async start(): Promise<void> {
    await super.start();
    await this.apiCall('ghostProducer', {
      body: {
        action: 'start_session',
        switcherId: this.switcherId,
        style: this.style,
        confidenceThreshold: this.confidenceThreshold,
        agentControlled: true,
      },
    });
  }

  async switchToSource(sourceId: string, reason: string): Promise<void> {
    await this.apiCall('switcher', {
      body: { action: 'switch', switcherId: this.switcherId, sourceId, transition: 'mix', duration: 500, reason },
    });
  }

  async showGraphic(templateId: string, data: Record<string, unknown>): Promise<void> {
    await this.apiCall('graphicsEngine', {
      body: { action: 'show', switcherId: this.switcherId, templateId, data },
    });
  }

  async markHighlight(label: string): Promise<void> {
    await this.apiCall('replay', {
      body: { action: 'mark_poi', switcherId: this.switcherId, label, timestamp: Date.now(), autoGenerated: true },
    });
  }
}
